### ISSUE TITLE
Abstract over camera control events

### ISSUE THREAD

**Issue by aepsil0n** [PistonDevelopers/cam#36]
To make this library more modular and composable, I suggest modelling the camera control events in a more abstract fashion. For once, this would allow one to separate key bindings from the controller logic. It would also allow users to interface with other input event libraries, e.g. glutin, without routing this through other piston libs.

An example could look somewhat like this:

```rust
pub enum FPSCameraControlEvent {
    Move(Direction),
    Stop,
    Rotate(...),
    ...
}
```

**Comment by bvssvni** [comment]
I have thought over this a bit and would prefer a set of functions that does the math, and decouple it with how it is represented.

The current design is based on the idea that `Camera` is the state, while its actually transformed from one structure to another. There is no "right" state of a camera because there are multiple ones.

`FirstPersonSettings` could be refactored away from `FirstPerson` and it would be named better as `CameraView` or something. This would then be an equivalent valid state as `Camera`.

Perhaps we should think of refactoring it into functions that takes the input as arguments and computes the output.

**Comment by bvssvni** [comment]
When we redesign, we should try to do as much as possible without breaking stuff first and then move stuff we are not happy with into another library. If there is something that we don't know how to do right, then do as little as possible. "Do as little as possible" usually means don't add new objects or state.

**Comment by bvssvni** [comment]
Closing because outdated.
